version: "3"
services:
  monitor:
    image: dockersamples/visualizer
    volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 9000:8080
    deploy:
      placement:
        constraints: [node.role == manager]
  
